apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "postgres://user:password@db:5432/biryani"
